### ISSUE TITLE
[jaeyong branch] 배틀체스 PUN2 개발 중 체크해야 할 것

### ISSUE THREAD

**Issue by ggjae** [TIOGx/battlechess#4]
- [x] Lobby에서 정확한 방 접근이 가능한지
- [x] 턴 종료시 상대 턴으로 전환
- [x] 버튼 OnClick 함수 작동 - Attack, 기물 생성으로 이동
- [x] 자신의 턴이 아닐때 기물을 클릭 - PieceStatus로 이동
- [x] 자신의 턴일때 기물을 클릭 - Move로 이동
- [x] ~~빈 화면을 클릭~~ - Bug#2 => 
UI에 UI 태그, Map에 Map 태그를 줌으로써 이 태그가 아니면 빈 화면이라고 판단하게 만듦.
비효율을 띄는지 한번 회의시간에 토론해보고, 더 좋은 아이디어를 찾아 개선해보자. **20210909 해결**

## 기물 생성

- [x] 기물의 정보가 맞게 생성되었는지
- [x] 기물의 Attackable, Movable 확인
- [x] Animation - Bug#3 **20210908 해결**

## Move
- [x] 타일의 Highlight & Animation
- [x] 카메라의 이동
- [x] 이미 있는 타일로 이동이 되지 않는지
- [x] 이동 후 Board 동기화
- [x] 이동 후에도 기물의 정보가 정확하게 반영 (Movable false)

## PieceStatus
- [x] 정확한 Status가 담겨있는지 (HP, Attack Power, Piece Type)
- [x] 카메라의 이동 - Bug#2 **20210909 해결**

## Attack
- [x] 전투시 기물의 전체의 공격이 일어나는지
- [x] 데미지가 표시되는지 - Bug#5 **20210908 해결** => 안 이뻐서 수정해야함
- [x] HP 반영이 이루어지는지 - Bug#5 **20210908 해결**

### bug

- 창모드로 게임 실행 시 UI의 위치가 맞지 않음 **1920x1080 해상도 고정**
- 빈 화면 클릭시 카메라가 Initialize 되지 않음 // 상태창보기위해서 클릭하면 왼쪽으로 밀리게해놨어 
- White Piece Animation
> ~해결 방법 : 기존 프리팹 animator 확인~ 해결
- White Warrior Bishop Rotation
> ~해결 방법 : 기존 프리팹 Rotation 확인~ 해결
- White Warrioir Bishop Attack
> ~해결 방법 : PieceController Script 코드 확인, 공격하는 White 측면에서만 Attack이 일어남~ 해결
